# Generated by Django 5.1.2 on 2024-11-22 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'etiqueta', 'url'],
                'permissions': [('view_mine_fav', 'Ver Mis Favoritos'), ('add_mine_fav', 'Agregar Mis Favoritos'), ('change_mine_fav', 'Actualizar Mis Favoritos'), ('delete_mine_fav', 'Eliminar Mis Favoritos'), ('add_ad_mine_fav', 'Agregar Mis Favoritos (Acceso Directo)'), ('delete_ad_mine_fav', 'Eliminar Mis Favoritos (Acceso Directo)')],
                'unique_together': {('user', 'url')},
            },
        ),
    ]
