# Generated by Django 5.1.2 on 2024-11-25 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igs_app_favorito', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together=set(),
        ),
    ]
